# Generated by Django 4.2.3 on 2023-08-02 06:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('category 1', 'Category 1'), ('category 2', 'Category 2'), ('category 3', 'Category 3')], max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('meta', jsonfield.fields.JSONField(null=True)),
                ('seo', jsonfield.fields.JSONField()),
            ],
        ),
    ]
