# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3')], max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default='null', upload_to='images/')),
                ('description', models.TextField(default='', max_length=200)),
                ('meta', models.TextField(blank=True, default='null', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='', max_length=100)),
                ('meta_description', models.CharField(default='', max_length=200)),
                ('meta_keywords', models.TextField(default='')),
            ],
        ),
    ]
