# Generated by Django 4.1.10 on 2023-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_student_admission_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
