# Generated by Django 4.1.10 on 2023-07-28 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_student_admission_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='class_passed_in_2023',
            field=models.CharField(choices=[('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_admission',
            name='language_medium',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Odia', 'Odia'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_admission',
            name='percentage_scored',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
