# Generated by Django 4.2.3 on 2023-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_course_meta_alter_course_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courses',
            field=models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3')], max_length=10, null=True),
        ),
    ]
