# Generated by Django 4.2.3 on 2023-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_course_meta_alter_course_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
