# Generated by Django 4.2.3 on 2023-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='seo',
            field=models.TextField(default=None),
        ),
    ]
