# Generated by Django 4.2.3 on 2023-07-31 08:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_contactmessage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None),
        ),
    ]
