# Generated by Django 4.2.3 on 2023-07-31 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_contactmessage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='percentage_scored',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
