# Generated by Django 4.2.3 on 2023-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_student_admission_percentage_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='parent_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_admission',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
