# Generated by Django 4.2.3 on 2023-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_student_admission_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_admission',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
