# Generated by Django 4.2.3 on 2023-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_student_admission_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_admission',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
